### ISSUE TITLE
Provide Grid Style

### ISSUE THREAD

**Issue by mehmettasar** [appreciated/material#13]
It would also be great to have a grid scss

**Comment by appreciated** [comment]
Hello there! Could you please specify "grid" more precisely? 
Do you mean providing styling for the v-grid (which is ~ [Material Data Tables](https://material.io/guidelines/components/data-tables.html#))? 
Or do you mean providing styles for a [Material Grid](https://material.io/guidelines/components/grid-lists.html#grid-lists-specs) (which would actually be ~ v-csslayout)?

**Comment by mehmettasar** [comment]
Hello,
I mean providing styling for the vaadin grid.
https://vaadin.com/docs/-/part/framework/components/components-grid.html

**Comment by appreciated** [comment]
I just released version 0.8.5. Let me know what you think, and when I missed something.
