### ISSUE TITLE
Valo-menu is becoming unusable in mobile resolution.

### ISSUE THREAD

**Issue by evrenism** [appreciated/material#15]
Sample screenshot; https://ibb.co/nmNfuk

**Comment by appreciated** [comment]
If you want me to fix this, it would be nice if you could provide me the code to reproduce it.

**Comment by evrenism** [comment]
You can generate the problem by adding an add-on to the Vaadin Dashboard Demo project. This project contains an example of a valo-menu.

https://github.com/vaadin/dashboard-demo

Thanks for your work

**Comment by appreciated** [comment]
Checkout the new version and give me some feedback for the fix!

**Comment by evrenism** [comment]
It's very nice, thank you.

I guess the shadow of the menu continues to be seen when the menu is closed.

**Comment by appreciated** [comment]
I will fix that in the next version ;)
