### ISSUE TITLE
Twin col selection bug

### ISSUE THREAD

**Issue by dinumihnea** [appreciated/material#20]
Overflow text on the selection item on horizontal scroll is hiden.
Normal  (not selected item)
![normal](https://user-images.githubusercontent.com/20513656/28720055-bef070d8-73b4-11e7-937f-898e866f78c5.jpg)
With bug
![selection-bug-twin-col](https://user-images.githubusercontent.com/20513656/28720084-cf3a3f32-73b4-11e7-89bf-08922e1eb99e.jpg)

**Comment by appreciated** [comment]
Thank you very much for the finding. Fixed it!
