### ISSUE TITLE
Grid scrollbar problem

### ISSUE THREAD

**Issue by dinumihnea** [appreciated/material#25]
Hello my friend.
I found a problem with scrollbar in grid. 
I think the problem is:
(v-grid.scss line 42)
 ```
 .v-grid-tablewrapper {
    overflow: visible;
  }
```
Please replace overflow value with **hidden**;

Thanks

**& Bonus for great addon:** :-)
//scrollbar custom
  ```
  *::-webkit-scrollbar {
        height: 16px;
        overflow: visible;
        width: 16px;
    }
    *::-webkit-scrollbar-button {
        height: 0;
        width: 0;
    }
    *::-webkit-scrollbar-corner {
        background: transparent;
    }
    *::-webkit-scrollbar-thumb {
        background: rgba(0,0,0,.2);
        background-clip: padding-box;
        border: solid transparent;
        min-height: 28px;
        padding: 100px 0 0;
        -webkit-box-shadow: inset 1px 1px 0 rgba(0,0,0,.1), inset 0 -1px 0 rgba(0,0,0,.07);
        box-shadow: inset 1px 1px 0 rgba(0,0,0,.1), inset 0 -1px 0 rgba(0,0,0,.07);
    }
    .v-grid-scroller::-webkit-scrollbar-thumb{
        border-radius: 0;
        border: solid transparent;
        background: rgba(0, 0, 0, 0.2); 
        -webkit-background-clip: content-box;
        background-clip: content-box;
    }
    *::-webkit-scrollbar-track {
        background-clip: padding-box;
        border: solid transparent;
        border-width: 0 0 0 4px;
    }
```

**Comment by appreciated** [comment]
Hello Dinu!

Unfortunately I cannot reproduce the Issue 😞.  For me the Scrollbar in .v-grid looks just fine. Could you explain the issue more thoroughly?

The 

````
.v-grid-tablewrapper {
   overflow: hidden;
 }
````
causes other issues in the top right corner

### visible
![visible](https://user-images.githubusercontent.com/1729845/29168240-59946202-7dce-11e7-99da-91a470852636.PNG)
### hidden
![hidden](https://user-images.githubusercontent.com/1729845/29168241-599c2e60-7dce-11e7-9d4e-918c6e14e1ba.PNG)

Thank you for your code, I hope you won't mind if i decrease the default width of the scrollbar. And make it adjustable via a variable.

**Comment by dinumihnea** [comment]
I agree, but the problem is with horizontal scroll.

![scroll bug](https://user-images.githubusercontent.com/20513656/29168652-8293b45a-7dd8-11e7-80e7-b7219a24008f.jpg)

**Comment by dinumihnea** [comment]
Test your grid with longs rows

**Comment by appreciated** [comment]
Thanks again for the finding 👍 

FYI: The problem is not the overflow, but the 
````
.v-grid-tablewrapper {
    position: absolute;
}
````
The following fixes it, but ill make sure to make the bottom scrollbar transparent before updating the addon.. 
````
.v-grid-tablewrapper {
        position: unset;
}
````
Thank you very much for your time!

**Comment by dinumihnea** [comment]
You're welcome

**Comment by appreciated** [comment]
Checkout if the new version fixes it properly
