### ISSUE TITLE
Maven is not able to find this dependency for theme add on  

### ISSUE THREAD

**Issue by sohimankotia** [appreciated/material#26]
Maven is not able to find this dependency for theme add on . I tried with adding repo in pom.xml but still maven is not able to find .

**Comment by appreciated** [comment]
May I have a look at your pom.xml and the error message of Maven?

How did you create your project, did you use one of Vaadin's [Maven archetypes](https://vaadin.com/maven#archetypes)?

**Comment by appreciated** [comment]
I created a working Maven project for you:
[material-addon-test.zip](https://github.com/appreciated/material/files/1226657/material-addon-test.zip)

How to reproduce it yourself: 
1. Create a basic Maven based Vaadin project by using an archetype (the IDE you might use also offers another way to do this)
````
mvn archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=vaadin-archetype-application -DarchetypeVersion=8.1.1
```` 
2. [Follow these steps](https://github.com/appreciated/material/wiki/Installation)

Let me know if it worked or not 😁

**Comment by sohimankotia** [comment]
Thanks for response . 

Yes , I used maven archetype .

I tried those . 

Error I am getting is : 

`Could not resolve dependencies for project com.sohi:vaadin-ui-example-book:war:1.0-SNAPSHOT: Failed to collect dependencies for [javax.servlet:javax.servlet-api:jar:3.0.1 (provided), com.vaadin:vaadin-server:jar:8.1.1 (compile), com.vaadin:vaadin-push:jar:8.1.1 (compile), com.vaadin:vaadin-client-compiled:jar:8.1.1 (compile), com.vaadin:vaadin-themes:jar:8.1.1 (compile), com.github.appreciated:material:jar:LATEST (compile)]: Failed to read artifact descriptor for com.github.appreciated:material:jar:LATEST: Failed to resolve version for com.github.appreciated:material:jar:LATEST: Could not find metadata com.github.appreciated:material/maven-metadata.xml in local`


Here is my pom -

`

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">


    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sohi</groupId>
    <artifactId>vaadin-ui-example-book</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>vaadin-ui-example-book</name>
    <prerequisites>
        <maven>3</maven>
    </prerequisites>
    <properties>
        <vaadin.version>8.1.1</vaadin.version>
        <vaadin.plugin.version>8.1.1</vaadin.plugin.version>
        <jetty.plugin.version>9.3.9.v20160517</jetty.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        
        <vaadin.widgetset.mode>local</vaadin.widgetset.mode>
    </properties>

    <repositories>
        <repository>
            <id>vaadin-addons</id>
            <url>http://maven.vaadin.com/vaadin-addons</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-server</artifactId>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-push</artifactId>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-client-compiled</artifactId>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-themes</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.appreciated</groupId>
            <artifactId>material</artifactId>
            <version>LATEST</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    
                    <packagingExcludes>WEB-INF/classes/VAADIN/widgetsets/WEB-INF/**</packagingExcludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>update-theme</goal>
                            <goal>update-widgetset</goal>
                            <goal>compile</goal>
                            
                            
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.0.0</version>
                
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>src/main/webapp/VAADIN/themes</directory>
                            <includes>
                                <include>**/styles.css</include>
                                <include>**/styles.scss.cache</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty.plugin.version}</version>
                <configuration>
                    <scanIntervalSeconds>2</scanIntervalSeconds>
                </configuration>
            </plugin>
        </plugins>
        <resources>
        <resource>
            <directory>src/main/resources</directory>
        </resource>
        </resources>
    </build>

    <profiles>
        <profile>
            
            <id>vaadin-prerelease</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>

            <repositories>
                <repository>
                    <id>vaadin-prereleases</id>
                    <url>http://maven.vaadin.com/vaadin-prereleases</url>
                </repository>
                <repository>
                    <id>vaadin-snapshots</id>
                    <url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>vaadin-prereleases</id>
                    <url>http://maven.vaadin.com/vaadin-prereleases</url>
                </pluginRepository>
                <pluginRepository>
                    <id>vaadin-snapshots</id>
                    <url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>

</project>
`

**Comment by appreciated** [comment]
Since It seems that you are missing all the depedencies not only the material theme, have you tried to run a `clean install` goal?

On which maven goal you try to execute you get the error message described?

You might consider contacting me via email, so we can speed up the communication.

**Comment by sohimankotia** [comment]
Hi,

Yes, I am running mvn clean install .

If I remove


        <dependency>
            <groupId>com.github.appreciated</groupId>
            <artifactId>material</artifactId>
            <version>LATEST</version>
        </dependency>

dependency , everything is fine . I am able to run vaadin project .


Thanks and Regards
Sohi

**Comment by appreciated** [comment]
If I take your POM and purge my local Maven repository before and run a `mvn clean install` it works.

- What is mavens output of the `mvn -v` command?
- Have you tried purging your local Maven repository, it happens rarely that the dependencies do not get downloaded properly, executing `mvn dependency:purge-local-repository` can fix this, by deleting the local repository and reinstalling it.
- [Maybe replacing the `<version>LATEST</version>` with `<version>1.0.6</version>`  could help since it is not supported anymore](https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency)

**Comment by appreciated** [comment]
Still having troubles?

**Comment by sohimankotia** [comment]
Sorry for late reply. That purging local repo solved problem .

Thanks for help .
