### ISSUE TITLE
Selection Mode Grid

### ISSUE THREAD

**Issue by Bugi82** [appreciated/material#28]
I have a problem with SelectionMode in Grid.

SelectionMode.SINGLE should select whole row and not just one cell and sidebars of ther cells with blue.
http://prntscr.com/gewp5j

SelectonMode.NONE select one cell and shuld select none
http://prntscr.com/gewop9

SelectionMode.MULTI should select all rows and cells
http://prntscr.com/gewo4s

**Comment by appreciated** [comment]
Thank you for reporting. Unfortunatly I'm currently on holidays, I'm gonna fix this during the next week.

**Comment by appreciated** [comment]
I just published an update. I hope it does actually fix the described problem. Let me know if it works, if it doesn't you are welcome to reopen this issue.

**Comment by Bugi82** [comment]
I have tested and in my case grid works. Thank you.
