### ISSUE TITLE
Live changing theme

### ISSUE THREAD

**Issue by fo0** [appreciated/material#29]
Is there a way to change the color of the theme dynamically and live ? Use case could be: User can change his theme...

`$mat-background-color: #fafafa; // #fafafa for a light and #303030 for a dark theme`

**Comment by appreciated** [comment]
Create two custom themes with different names (by default there is always a theme folder called "mytheme", simply duplicate it with the name f.e. "mytheme2") and change the variable values. 

You should then be able to change the theme via `UI::setTheme("mytheme2")` in runtime. 

[You can find a working example in the Valo Theme Test](https://github.com/vaadin/framework/tree/master/uitest/src/main/java/com/vaadin/tests/themes/valo)

I actually never tried to do this myself. If there any problems with the theme itself let ne know.

**Comment by fo0** [comment]
Great idea, thanks.

I'll let you know if it worked

**Comment by fo0** [comment]
Works like a charm. Thanks!
Maybe you want to add this to your wiki, if anyone else has this question, the answer could be found there.
