### ISSUE TITLE
Grid scrollbars in IE11

### ISSUE THREAD

**Issue by etemplar** [appreciated/material#31]
Hello,

First of all, thank you for the awesome theme.

I am facing the following situation: grid does not display scrollbars in IE.
They are being shown in Chrome and Firefox, also IE displays them if I change my app theme to Valo.
It is also reproducable in your demo, please see screenshots:

Demo:

![demo](https://user-images.githubusercontent.com/9402154/30480888-c0343bb4-9a24-11e7-8f73-3a70c89ace49.png)

My app (IE):

![localhostie](https://user-images.githubusercontent.com/9402154/30480898-cbbaec26-9a24-11e7-87d6-d0eb0a7e99ff.png)

My app (Chrome):

![localhostchrome](https://user-images.githubusercontent.com/9402154/30480902-d21ae288-9a24-11e7-94a0-eb92f5c56fca.png)

Any thougths?
Thanks in advance.

**Comment by appreciated** [comment]
You are welcome 😄. This seems to be a bug 😅 thank you for reporting it, I will have look into it later on.

**Comment by appreciated** [comment]
I can confirm the bug and the fix will be published tonight.
