### ISSUE TITLE
Last cell of grid's row drops to the next row

### ISSUE THREAD

**Issue by appreciated** [appreciated/material#34]
Code taken from [vaadin/framework/issues/10086](https://github.com/vaadin/framework/issues/10086) Issue initially reported by @mike392 

```
@bean
@scope("session")
public Grid getGrid() {
Grid grid = new Grid<>();
grid.setSizeFull();
grid.addColumn(DisplayPolygon::getFrequencyBand).setCaption(columnNames[0]);
grid.addColumn(DisplayPolygon::getEirp).setCaption(columnNames[1]);
grid.addColumn(DisplayPolygon::getBandwidth).setCaption(columnNames[3]);
grid.addColumn(DisplayPolygon::getSatelliteName).setCaption(columnNames[2]);
grid.setStyleName(MaterialTheme.TABLE_COMPACT);
return grid;
}
```
> When it's rendered - then you can see that last cell of the second row is pushed to the next row.

**Comment by appreciated** [comment]
@mike392 Seems like I will need some more information to fix this issue since I cannot reproduce it
<br>
![grid-issue](https://user-images.githubusercontent.com/1729845/31435428-c79ed584-ae7f-11e7-98df-21bd2e10c60c.PNG)
<br>
looks fine to me 🤔 (without the provided fix of yours)

Have you modified any further css?

**Comment by mike392** [comment]
Well, I'll try to reproduce it on my own and give you a github repository. Honestly, I've changed some css but it was not related to classes of grid. After removing of those paddings everything worked like charm.

**Comment by appreciated** [comment]
This would be really nice if you could find it for me 👍 The grid CSS is quite complicated, it better should not fiddle be with.

**Comment by mike392** [comment]
Hi, I have one example finally. Let me share the [repository](https://github.com/mike392/MaterialThemeGridBugSample) with you.

Here's the stuff which I was talking about - it is WITH padding  uncommented
![image](https://user-images.githubusercontent.com/16647651/31540050-2dda038e-b013-11e7-9438-61155ec354a8.png)

**Comment by mike392** [comment]
Honestly, I've tried to override some styles of the gird in my own scss file. But anyways if you try to omit the styles and re-compile the theme the effect remains the same.

**Comment by appreciated** [comment]
The new version should fix the issue finally, please verify if the issue is fixed

**Comment by appreciated** [comment]
@mike392 could you please close the [related issue in the Vaadin Framework](https://github.com/vaadin/framework/issues/10086)?

**Comment by mike392** [comment]
Yes, sure! Sorry for inconvenience!
