### ISSUE TITLE
Grid inside a popup is tending to shrink when scrollable

### ISSUE THREAD

**Issue by mike392** [appreciated/material#35]
The problem is that for some reason **v-grid-tablewrapper** or **v-grid-scrollable-vertical** are trying to shrink the Grid - it happens when I re-set items of grid and do refreshAll on DataProvider.
![image](https://user-images.githubusercontent.com/16647651/32737184-6bdb580e-c8aa-11e7-9bbb-02c7237b4e2b.png)
When I press CLEAR FILTERS (please, don't mind the caption name) - it constantly decreases the height for the style values highlighted
![image](https://user-images.githubusercontent.com/16647651/32737421-0cbd4b24-c8ab-11e7-91a2-7ef20800633d.png)
It happens ONLY when there are scrolls on the grid - when there are no scrolls then everything works like charm.
I have a reproducable sample within the repository given below
https://github.com/mike392/MaterialThemeGridBugSample

Thank you so much in advance! It's quite an annoying thing:)

**Comment by appreciated** [comment]
Welcome back!
> I have a reproducable sample within the repository given below https://github.com/mike392/MaterialThemeGridBugSample

I looked at your example and it really doesn't look good. When finding/fixing the kind of bugs I always check if it works with plain Valo first. If I remove all your sass with only this left:
```
@import "../valo/valo.scss";

@mixin facebook {
  @include valo;
}
```
And recompile the theme it does also not work this means that I'll handle this a `Feature` (not a bug) which I intend not to change. I think your `Problem` lays actually in the Component you are using to display the grid, in this case -> PopupView. 
Have you tried using [(Sub-)Windows](https://vaadin.com/docs/framework/layout/layout-sub-window.html) instead?

**Comment by mike392** [comment]
Well, actually I haven't tried yet - but it really seems kinda strange. Because it happens ONLY when the grid gets scrollable - I don't knowexactly where the problem occurs, I can assume that it may be even a framework issue, because after a certain request-response handling via Vaadin servlet where something with a constant WRAP_* is processed there appears this decrease in height. 

I suppose there should be no difference whether I use popup or Sub-window... It seems like there is a kind of grid wrapper which processes grid's dimensions in a suspicious way.

Anyway thank you for the advice - I'll try this one for sure.

**Comment by mike392** [comment]
I've updated the [repository](https://github.com/mike392/MaterialThemeGridBugSample) - please, don't mind the code quality as it's messy and too straightforward. It was just to demonstrate the effect.

The sample was made for window and the effect remains the same, unfortunately...

**Comment by appreciated** [comment]
Your example still doesn't work with Valo (there needs to be set a height). If it works with Valo and doesn't with Material then come to me again.

**Comment by mike392** [comment]
then should I place the issue in framework?

**Comment by appreciated** [comment]
First of all I don't think it is a Vaadin bug. 
If you add a component with the height of `100%` to a layout with a height of `auto` the component won't get any height. In this case your Window has no specific height, and Spring adds automatically a height of `100%` to your grid. Try to set either the height of the window or to change the height of the grid to a `non percentage value`.

**Comment by mike392** [comment]
Honestly, I tried to set explicit height for everything... Still no luck. I'll try to set explicit height for Valo in order to get it running so that you could see it in Valo...

**Comment by mike392** [comment]
Well, I guess you were right when telling me to remove stuff like setSizeFull (i.e. size in percentage). I can see it working now on my sample project - I'll try to adjust it to the main one then... Thank you anyway for your assistance!

**Comment by appreciated** [comment]
You are welcome 😉
