### ISSUE TITLE
Can not remove the grid header

### ISSUE THREAD

**Issue by evrenism** [appreciated/material#36]
When grid.removeHeaderRow(0) is executed, the header continues to appear on the page.

![screenshot-192 168 10 41-8080-2017-11-23-15-23-55-752](https://user-images.githubusercontent.com/30319905/33173146-feed622a-d063-11e7-89d8-ba48d6ac40dd.png)

**Comment by appreciated** [comment]
Hello! thank you very much for reporting this issue. Can you confirm that is was fixed in version 1.1.6?

**Comment by evrenism** [comment]
Yes, its fixed. Thank you very much.
