### ISSUE TITLE
Button height constant when "v-button.floating-action" is used.

### ISSUE THREAD

**Issue by evrenism** [appreciated/material#37]
Hi,
When the theme font size($v-font-size) is enlarged; Despite the growth of the other buttons, the floating buttons remain small. Would not it be better to use 'v-unit-size' for 'v-button.floating-action'?

![v-font-size](https://user-images.githubusercontent.com/30319905/33481078-0527bdde-d6a4-11e7-8996-f43f1206d2bc.png)

**Comment by appreciated** [comment]
I agree a constant value of `56px` is not a good solution here, better would be something like ~ `v-unit-size * 1.25` in [v-button.scss](https://github.com/appreciated/material/blob/master/material-addon/src/main/webapp/VAADIN/themes/material/components/v-button.scss#L211-v-button.scss#L212) and [here](https://github.com/appreciated/material/blob/master/material-addon/src/main/webapp/VAADIN/themes/material/components/v-button.scss#L224-v-button.scss#L226). I'll have to do some investigation here this might take some time.

**Comment by appreciated** [comment]
Thank you again for reporting this issue! Can you (again) confirm that is was fixed in version 1.1.7 😁?

**Comment by evrenism** [comment]
Thank you so much, it's been so beautiful

**Comment by evrenism** [comment]
I'm sorry to notice late. I think the button and the icon should be in different widths. In this case, the SVG icons cover the entire button.

![adsiz](https://user-images.githubusercontent.com/30319905/34336300-05fc28d2-e967-11e7-80f8-5cdb7a783b6c.png)
