### ISSUE TITLE
The SVG icons cover the entire button

### ISSUE THREAD

**Issue by evrenism** [appreciated/material#39]
I'm sorry to notice late. I could not test the previous solution correctly (#37 ). In the current situation the SVG icons cover the entire button. I think the width of the button and the icon should be different. (.v-button.floating-action, .v-button.floating-action .v-icon)

![adsiz](https://user-images.githubusercontent.com/30319905/34355368-bc79aca4-ea45-11e7-821b-1595d725f98f.png)

**Comment by appreciated** [comment]
> I'm sorry to notice late.

No Problem!

>  I could not test the previous solution correctly (#37 ). In the current situation the SVG icons cover the entire button. I think the width of the button and the icon should be different. (.v-button.floating-action, .v-button.floating-action .v-icon)

Could you please provide some example code?

**Comment by evrenism** [comment]
```java
...
Button cookButton = new Button(new ThemeResource("image/cook.svg")); //(size: 150px x 150px)
cookButton.addStyleNames(MaterialTheme.BUTTON_FLOATING_ACTION, MaterialTheme.BUTTON_DANGER, MaterialTheme.BUTTON_ICON_ONLY);
layout.addComponent(cookButton);
...
```


![float-action](https://user-images.githubusercontent.com/30319905/34373597-216d67de-eaed-11e7-835e-30d1fad15ca2.png)
