### ISSUE TITLE
.sketch would be an AMAZING time-saver. Possible?

### ISSUE THREAD

**Issue by TeddyGraphics** [appreciated/material#44]
I am to redesign (UI/UX) a service made on top of Valo and a .sketch file for Material Theme would be a huge timesaver. Do you happen to have one?

Thanks a tone in advance 🙏
Piotr from TeddyGraphics.com

**Comment by appreciated** [comment]
Unfortunatly no :disappointed:. But you might find some for [Materialize](https://github.com/Dogfalo/materialize) on which this theme is partly based.
