### ISSUE TITLE
Hamburger menu for column hiding in grid is not visible

### ISSUE THREAD

**Issue by OSchwark** [appreciated/material#45]
Hello,
unfortunately the hamburger menu to hide/unhide columns is not visible (I am using Vaadin 8.6.1 but from comment in Vaadin Directory it is also not working in Vaadin 8.3). Looks like it is overlayed by the last header-cell.
Here is the menu (screenshot from firefox developer console with menu highlighted on page):
![menu](https://user-images.githubusercontent.com/8201232/48834321-d250b680-ed7d-11e8-9002-29260b60955e.png)
That is on top:
![menu_overlayed](https://user-images.githubusercontent.com/8201232/48834329-d7156a80-ed7d-11e8-9cce-a4243b915084.png)

Is there any workaround for this? I already tried to make the last cell neither sortable nor resizeable. If I set one of the columns before to a smaller width (so there is some space between last column and grid border) the button is there (but not really visible) and the opened menu is also rendered but also not visible (only if hovered).

Opened but not hovered:
![opened_not_hovered](https://user-images.githubusercontent.com/8201232/48834791-e943d880-ed7e-11e8-82be-00e2b6fd59b4.png)
Opened, hovered:
![opened_hovered](https://user-images.githubusercontent.com/8201232/48834797-ee088c80-ed7e-11e8-9c60-558d6391d88b.png)

Please let me know if I can provide any further information or try any workaround.

Best regards
Olli

**Comment by appreciated** [comment]
Hey Olli sorry for my late response, as you might have noticed I'm currently pretty busy with other projects of mine. Just to let you know, I won't leave you hanging. Give me some time.

**Comment by OSchwark** [comment]
Hey,
Thank you very much. Didn't thought it would go live so fast :)

Will use it soon.

Best regards
Olli

Am Sa., 16. Feb. 2019, 11:42 hat appreciated <notifications@github.com>
geschrieben:
