### ISSUE TITLE
Customization - Grid Row Height

### ISSUE THREAD

**Issue by bram-pkg** [appreciated/material#47]
Is there a way to change the default row height for grids, or at least the padding on top and below the text in a grid?

**Comment by appreciated** [comment]
@BramCeulemans have you checked out the [valo variables](https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_grid.scss)?

**Comment by bram-pkg** [comment]
Sorry, I did notice those. Thought since your grid row height is different it was a customization that you made.

**Comment by appreciated** [comment]
[For details check out the following](https://github.com/appreciated/material/blob/master/material-addon/src/main/webapp/VAADIN/themes/material/components/v-grid.scss#L66-L71)
