### ISSUE TITLE
Active button style on mobile devices

### ISSUE THREAD

**Issue by milomirtopic** [appreciated/material#5]
After clicking the button will keep active style on mobile devices until some other component is clicked.

**Comment by appreciated** [comment]
Fix is already in but well, not too proud of it, maybe you might know how to solve it correctly with SASS. 
[Before](https://github.com/appreciated/material/blob/5241b79f54460c794d859f4b74989d777fea8881/material-addon/src/main/webapp/VAADIN/themes/material/components/v-button.scss) -> [After](https://github.com/appreciated/material/blob/master/material-addon/src/main/webapp/VAADIN/themes/material/components/v-button.scss)

If you continue to experience bugs please let me know (I'll set this for now on review).
Tested the on Android Chrome, Desktop Chrome, Firefox and Edge.
