### ISSUE TITLE
Problem with Material Design on Vaadin 14

### ISSUE THREAD

**Issue by KaesDingeling** [appreciated/material#59]
I use AppLayout on version: `4.0.0.rc5` and Vaadin on version: `14.1.28`

I can't tell the difference between the menu and the application. In general, there seems to be a lack of style in the presentation.
![grafik](https://user-images.githubusercontent.com/19664730/83085989-d30e8b00-a08d-11ea-9ee1-24a7878eb897.png)

My RouterLayout:
![grafik](https://user-images.githubusercontent.com/19664730/83086166-4dd7a600-a08e-11ea-9e8e-7b5732887385.png)

Link on a view:
![grafik](https://user-images.githubusercontent.com/19664730/83086204-647dfd00-a08e-11ea-88bf-05def75801d2.png)

Under Lumo the design is correct.

**Comment by appreciated** [comment]
Hi @KaesDingeling, It seems that you opened an issue for the [`vaadin-app-layout`](https://github.com/appreciated/vaadin-app-layout) under my [Material theme repository for Vaadin 8](https://github.com/appreciated/material) 😁.  Would you mind reopening it on the other repository?

**Comment by KaesDingeling** [comment]
Sorry, I guess it was too late at night. I'll open the issue in the right repository.

**Comment by appreciated** [comment]
[Thanks I opened an issue for this](https://github.com/appreciated/vaadin-app-layout/issues/332)
