### ISSUE TITLE
Ripple effects

### ISSUE THREAD

**Issue by TheSalsaest** [appreciated/material#9]
While it is true that a pure click-based ripple is not attainable with pure CSS, what about a centered ripple?
It would be still more communicative than no effect at all.

For instance, a working sample (not mine) can be foundhttps://github.com/mladenplavsic/css-ripple-effect

**Comment by appreciated** [comment]
The library you mentioned seems to have a bug when clicking buttons with an uneven pixel width. I'll see what i can do to fix this.

**Comment by appreciated** [comment]
I just added centered ripple effects to the buttons, but i needed to remove all Valo button styles to make it work. This causes some other issues which need to be fixed before I can release it at Vaadin Addons.
